apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
  labels:
    app: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword-change-me"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
  MYSQL_PASSWORD: "wordpresspassword-change-me"
