apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
  - namespace.yaml
  - mysql/secret.yaml
  - mysql/pvc.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - wordpress/pvc.yaml
  - wordpress/deployment.yaml
  - wordpress/service.yaml
  - wordpress/service-nodeport.yaml
  - ingress.yaml
